### ISSUE TITLE
[TODO Roundup] Result Management Functionality

### ISSUE THREAD

**Issue by JackUrb** [facebookresearch/Mephisto#100]
# Summary
The mephisto `DataBrowser` class is just getting started, and needs to be extended with a bunch of common use cases for browsing data. 
- [ ] Query by worker
- [ ] Find incomplete assignments from a task run
- [x] Query workers by qualification #591
- [ ] Find onboarding task for agent #600
- [ ] Find task run details
- ...

**Comment by pringshia** [comment]
Any thoughts on what other features we could add to the DataBrowser? The Review CLI is also another tool we have now. I'm planning on writing up some documentation on the different review options this half.
