### ISSUE TITLE
[Ongoing] New Examples

### ISSUE THREAD

**Issue by JackUrb** [facebookresearch/Mephisto#712]
# Overview
Mephisto can always use more `examples` to show how key functionality can be used, and to serve as a starting point for people to build specific projects from. This issue catalogs some of the things that we _know_ we want or are missing, though we're also always happy to add other examples (or links to other projects using Mephisto in cool ways!).

# TODO Examples:
- [x] Model-in-the-loop (Done in #677)
- [ ] Example using [gold labeling](https://mephisto.ai/docs/guides/how_to_use/worker_quality/using_golds)
- [x] Example using [screening units](https://mephisto.ai/docs/guides/how_to_use/worker_quality/using_screen_units)
- [ ] Example active learning task? (Starter code in #312, salient part involves using a static_task_data generator rather than a static array). 
- [ ] Multimodal chat? (Starter code in #328, but needed expansion + a public scene to use).
- [ ] ...
