### ISSUE TITLE
[TODO Roundup] Improve example starting flow

### ISSUE THREAD

**Issue by JackUrb** [facebookresearch/Mephisto#95]
# Summary
The existing examples have a few issues with running on their first launch. As of now, if you want to launch on sandbox and see how that works, you need to manually update constants in the script, and uncomment some lines to ensure you can create a requester, potentially modify the input arguments, etc.

Ideally the arguments and location could be configured on the command line, and there would be no need to create a requester by uncommenting.

# Requirements
- [x] Update the example scripts to be able to set their flags (like `USE_LOCAL`) using command line flags.
- [x] Update the example scripts to be able to set the arguments actually passed to the operator using command line flags. (likely after #94 is completed)
- [x] Create utility functions for forcing the retrieval of a requester by provider type. This flow would involve trying to query for any of them (defaulting to the most recently created) but asking the user to create the requester otherwise (see the flow for getting [required requester arguments](https://github.com/facebookresearch/Mephisto/blob/511cb19402a390d08c6c411bbf547d9d042a22ce/mephisto/client/api.py#L117) and [registering a new requester](https://github.com/facebookresearch/Mephisto/blob/511cb19402a390d08c6c411bbf547d9d042a22ce/mephisto/client/api.py#L125) from the frontend for an example).
- [x] Add missing configuration options to some examples.
# Stretch
- [ ] Add native JSON parsing for initial task data.
