### ISSUE TITLE
[TODO Roundup] Improve Operator Flow

### ISSUE THREAD

**Issue by JackUrb** [facebookresearch/Mephisto#96]
# Summary
Right now a lot of the functionality of the `Operator` class has been written 'to get it working' but hasn't been refactored into a useful API for users. One such example of this is the process for waiting for an operator to finish a task run (and dealing with cleanup), which exists in [every example file](https://github.com/facebookresearch/Mephisto/blob/511cb19402a390d08c6c411bbf547d9d042a22ce/examples/acute_eval_demo/example_script.py#L89). 

It would be useful to make Operator a little more robust and fleshed out by providing a method to suspend a thread until task runs are finished, and to update the existing `parse_and_launch_run` method to clean up after itself if it fails to initialize (+ logs #93).

# Requirements
- [x] Implement a `wait_for_task_runs` method (that accepts an argument for a log rate to visibly show a message about tasks that are still waiting) that replicates the behavior currently available in example files
- [x] improve the `wait_for_task_runs` method to have more robust error handling that passes through a few stages:
  - On an Exception, it displays the exception context and asks the human if they want to shut down or ignore the exception (with a simple (y)/n input). 
  - On an interrupt, it begins the shutdown process, first telling the user how many active tasks there are right now. At this point it asks if we want to interrupt those active tasks or wait for them to complete (also with a simple (y)/n input).
  - Following this interrupt, suspends the user's ability to ctrl-C during the rest of the shutdown process to ensure that the architect, supervisor, and operator are properly shut down.
- [x] Update the `parse_and_launch_run` method(s) to clean up after themselves if they run into a failure during the setup of a task.
