### ISSUE TITLE
[TODO Roundup] InitializationData Loading

### ISSUE THREAD

**Issue by JackUrb** [facebookresearch/Mephisto#99]
# Summary
At the moment data loading into Mephisto tasks is managed with a static list of `InitializationData` that is constructed at the moment of task launch. This doesn't work well with the idea of tasks that launch additional instances as time proceeds. As such if we want dynamic length tasks, we'll need to get the generator version of `InitializationData` working. We'll also need to update certain core assumptions about task status to determine the difference between a task that has all of its units complete vs one that just has its _currently generated_ units complete (and more may come later).

# Requirements
- [x] Make `TaskLauncher` `__init__` take an additional argument for `max_number_of_concurrent_units`. Create a version of `launch_units` that spawns a background thread to launch the units, and then that thread should rely on a generator that only returns a unit when there are less than the max in the "Launched/assigned" state. (There can be local state added to `TaskLauncher` to keep track of the units that are currently in the state, such that you only need to check on those rather than all units. It will also be useful to keep a list of currently unlaunched units). This thread should be exited after `expire_units` is called. Write a test case in the task_launcher_test.py that initializes a task launcher with a cap of 1, and ensure it only spawns 1 task at a time (and that completing that one task causes a second to launch)
- [x] Get the Generator version of InitializationData working (`grep InitializationData` to get started on extra context). This can be done by instead creating a thread for `TaskLauncher` that will be responsible for keeping track of both `launch_assignments` and `launch_units`. You can break this up into two subfunctions `try_launch_more_assignments` and `try_launch_more_units`, which start being called in the main thread after the corresponding `launch_x` function is called until `expire_units` is called. (#188)
- [x] Update `Operator` to handle properly shutting down when a task run has been completed. At the moment `TaskRun.get_is_completed()` is used in `_track_and_kill_runs` to see when a currently running task has no more units to work on before shutting down. This will no longer work properly if the operator is waiting on an assignment to be generated, as all of the already generated assignments may be completed, and this method will shut down a task that may still have assignments to come. As such, the `Operator` should be checking the `TaskLauncher` instead, and should only refer to `get_is_completed` when the `TaskLauncher`'s assignment generator thread is done. Also, the `TaskRun` should be updated to only call `self.db.update_task_run(self.db_id, is_completed=True)` and set the cached `__is_completed` value after the `Operator` sets a flag on the `TaskRun` to note that assignment generation is done.
- [x] Add the reconnection feature for live tasks, which requires updates to `Supervisor` and `Operator`. The general flow change will be that, if `task_args.get('requeue_incomplete_tasks')` is `True`, a `requeue=True` flag is passed to `TaskLauncher`. When this flag is set, upon initializing the task launcher, the launcher will create an empty `requeued_assignment_data` array, and wrap the `initialization_data_iterator` in a generator function that prioritizes returning elements from that array before from the initialization data iterator. Then, in the `Supervisor`, if in the `_launch_and_run_assignment` call's `finally` clause, if the `TaskLauncher` has an initialized requeued_assignment_data array, `TaskLauncher.requeue(assignment.get_assignment_data())` should be called to requeue that assignment. In order for this to work, the `Job` `RecordClass` will need to be updated to receive a `TaskLauncher` as well, and the `_launch_and_run_assignment` call should receive the job rather than just the `TaskRunner`.

**Comment by saraEbrahim** [comment]
Hey @JackUrb,
for last bullet point, why would the supervisor need a `TaskLauncher` in the `Job`' `RecordClass`? don't we need the `TaskLauncher` that's inside the `TaskRunner`?. 

And in order to add `TaskLauncher` in the `Job` named tuple, I'll need to pass it here with the other `Job` parameters:
https://github.com/facebookresearch/Mephisto/blob/b15a8f779c3490d4a0ee0d7c26a386f2d000a5ce/mephisto/core/operator.py#L253

How can I define a `TaskLauncher` in the `operator.py`?

**Comment by pringshia** [comment]
Just wanted to follow up for a status update on the last two tasks here. Are they still outstanding/now irrelevant/or done? We can also break out unfinished tasks from here into their own individual tasks.

**Comment by JackUrb** [comment]
I think these tasks should stay in this context for now. They're still relevant, just unfinished.

**Comment by JackUrb** [comment]
This was completed in #480.
